vapor/leaf

- Sources/Leaf/Tag/Models/Extend.swift
Small syntax change that prevents the compiler from crashing in certain situations.
> swift compiler crash fix

- Sources/Leaf/Link.swift
- Tests/LeafTests/LinkTests.swift
`Link` retained its children, which in turn retained their parent,
leading to a cycle and therefore a memory leak.
> Fixed a retain cycle

- Resources/if-empty-string-test.leaf
- Sources/Leaf/Tag/Models/If.swift
- Tests/LeafTests/IfTests.swift
This is something of a matter of opinion.
Currently, if a Node represents a blank string, using that node as the argument to `#if` will cause the block to render. I believe that `#if` should consider a blank string to be equivalent to `false`, in this case, and therefore not render.
In Polymorphic a `bool` has three states: true, false or nil, and `""` becomes nil, which makes sense. In this tag, `""` is considered not-nil and so returns true, rendering the block.
This patch and test causes `#if("")` to not render its block.
The alternative, and it's also a valid one, is to force the user of the `#if` tag to convert empty strings to false or nil before rendering.
> Proposal: #if(string) to not render if string is blank

- Resources/no-body-whitespace.leaf
- Resources/variable-body-whitespace.leaf
- Sources/Leaf/Buffer/Buffer+Leaf.swift
- Tests/LeafTests/BodyWhitespaceTests.swift
- Tests/LinuxMain.swift
All tests passing. 
Please let me know any feedback or if I've totally missed the mark on this one. Thanks.
#52
> Fix/fix 52 ‘#export()'depends on ‘{‘ location

- Tests/LeafTests/ContextTests.swift
The test checked the value and index, but not offset which is new in #56.
Just updated this one test. I made the grammar slightly shorter too as the line got a bit long.
> Test - Add check for new offset in loop test

- Sources/Leaf/Renderer/Renderer.swift
- Sources/Leaf/Service/Provider.swift
- Tests/LeafTests/LeafTests.swift
> Disable Leaf cache on development

- Package.swift
It's theoretically ready for a merge as far as I can tell and projects that depend only on Vapor and Leaf can safely use `rc.1` version of both (at least my short testing earlier today showed no obvious compatibility issues).
Realistically though, it may often result in an unsolvable dependency tree as Fluent doesn't have release candidate yet. So maybe waiting for tagging Fluent would make more sense? ¯\\\_(ツ)\_/¯
> Updated dependencies and prepared for RC

- Package.swift
Updated Leaf 3.0.0 dependencies to as of current date release versions – `template-kit 1.1.0` being the critical one.
> update dependencies for 3.0.0

- Sources/Leaf/Parser/LeafParser.swift
- Tests/LeafTests/LeafTests.swift
Fixes bug: #127
Parsing in-line comment should not join following line.
* Only-comment lines should be removed from output
* End-of-line comments should not remove following line break
> Fix parsing inline comments

- Package.swift
- Update to match new Vapor requirements for OS
- Require current Vapor beta version
- Leaf's major beta version has been bumped due to the new OS requirement (a breaking change), even though there are no changes to Leaf itself
> Beta 3 Update

- Sources/Leaf/LeafEncoder.swift
Removes force unwrapping in the LeafEncoder allowing for types to be Optional.
> Allow Optional values when encoding

- Sources/Leaf/LeafProvider.swift
- Tests/LeafTests/LeafTests.swift
LeafCache is now settable (#155, fixes #154). 
```swift
app.leaf.cache.isEnabled = false
```
> Make app.leaf.cache settable

- Package.swift
- Sources/Leaf/Application+Leaf.swift
- Sources/Leaf/Deprecated.swift
- Sources/Leaf/Request+Leaf.swift
- Tests/LeafTests/LeafTests.swift
This update aligns Vapor+Leaf bindings to use LeafKit 1.0.0rc-1.11 API changes for sandboxing and file security behaviors, and using multiple sources for raw Leaf templates:
* `LeafSources` stores multiple `LeafSource`*-adhering objects by name and maintains a default search order of which objects to attempt to read from
* `LeafSource` (previously `LeafFiles`) represents any object with a directed behavior for interpreting a template name into its own reading space (eg, a filesystem or database)
* `NIOLeafFiles` gains initialization configuration for sandboxing and reading-limit behavior
For more details, please refer to the associated LeafKit update:
[LeafKit 1.0.0rc-1.11: LeafSources, LeafSource and File Sandboxing/Limiting in NIOLeafFiles](https://github.com/vapor/leaf-kit/tree/1.0.0-rc …
> File Sandboxing, Directory Limiting, and Multiple Template Sources

- Package.swift
- Sources/Leaf/LeafEncoder.swift
- Tests/LeafTests/LeafTests.swift
This release exposes configuration methods for setting the default presentation output of data in rendered Leaf templates.
Static options are settable only until `app.leaf.renderer` is accessed or a `render(...)` call is made.
Stored property options in a `LeafConfiguration` may be used in various ways by a `LeafRenderer` which the configuration object was for, and changes to them after the object was provided to a specific `LeafRenderer` will have no affect.
```swift
.rootDirectory: String   // The default file directory used for file-system based `LeafSource`s                  
```
Static options on `LeafConfiguration` are effectively constant once any `LeafRenderer` has been instantiated and attempts to change them will assert in `Debug` and silently fail in `Release` to prevent …
> LeafConfiguration Formatting Options

- Sources/Leaf/Application+Leaf.swift
- Tests/LeafTests/LeafTests.swift
Disable the cache in Leaf's renderer when the environment is set to development.
Resolves #185
> Disable Leaf Cache for the Renderer in development

- Sources/Leaf/LeafEncoder.swift
- Tests/LeafTests/LeafTests.swift
Using arrays for top-level `Context`s in Leaf is not support. This changes the behaviour of Leaf to throw an error instead of `fatalError`ing and taking down the app.
Resolves #190
> Remove `fatalError()` when using array for `Context`

- Sources/Leaf/Application+Leaf.swift
This removes the log message that states that the application is starting the Leaf Renderer with caching enabled. Because the `userInfo` is unique per request we can't cache the `renderer` so it needs to be created for each request (which is fine as everything else is stored in the request's storage). However this means that we get the log for each request.
Additionally the log might not be true if the application is configured to disable caching. Resolves #192
> Remove Starting Renderer with Caching Enabled Log

- Package.swift
- Sources/Leaf/Exports.swift
Exports the new `UnsafeUnescapedLeafTag` so it's easy to use for anyone importing Leaf
> Export `UnsafeUnescapedLeafTag`

- Sources/Leaf/LeafEncoder.swift
- Tests/LeafTests/LeafTests.swift
UnkeyedContainer throw fatal error in case of encoding collection with one or more nil values.
This change removes force unwrap of the input data and skip any nil value in a collection.
Resolves #197
> Fix UnkeyedContainer crash for collections with nil

- Package.swift
This change allows Leaf to be used within iOS environments. Without it we get the following error:
`The package product 'Vapor' requires minimum platform version 13.0 for the iOS platform, but this target supports 9.0`
> Add experimental support for iOS

- Sources/Leaf/LeafEncoder.swift
This PR addresses issue https://github.com/vapor/leaf/issues/215 and server as an alternative of PR https://github.com/vapor/leaf/pull/216, that somehow got stuck in it's efforts of being merged in.
I've done 2 things to discover the issue and confirm the fix
- Xcode would show a bunch of memory leaks when using it's memory graph debugger, those are gone after the changes introduced in this PR
- I've switched https://swiftpack.co, which uses leaf heavily, to using my fork with this fix. The heroku graph bellow shows significantly lower memory consumption and does not seem to be crashing, though I still do do seem to have memory leaks somewhere in the codebase.
> Fix retain cycle(s) in encoder implementation

- Package.swift
- Sources/Leaf/LeafEncoder.swift
Swift Algorithms was used in Leaf but never explicitly declared as a dependency on the target. That resulted in compiler errors in some scenarios. The dependency is now correctly declared.
> Fix Algorithms Dependency Declaration

- .github/workflows/api-docs.yml
- .github/workflows/projectboard.yml
- .github/workflows/test.yml
- Package.swift
- README.md
- Sources/Leaf/Exports.swift
This officially cleans up the last repo left that still has an uncorrected `Exports.swift`. Cleans up the README and CI workflows too.
> Fix Exports.swift

- Package.swift
- README.md
This package should have gotten a release after the previous update to its `Package.swift`, but it was overlooked. This one further updates the versions and should resolve version issues with the Leaf provider.
> Bump Package.swift

- Package.swift
- Update to latest version of LeafKit to support time zones in `#date` tag.
- Update to latest version of Vapor.
- Set the minimum supported Swift version to 5.8
> Up Swift Version to 5.8

- Sources/Leaf/Application+Leaf.swift
- Tests/LeafTests/LeafTests.swift
Fixes an issue where the wrong type would be set to the `application` `userInfo` key when accessing the renderer directly on the `Application` (it would set a value of `Application.Leaf`, rather than `Application`, and then the casting would fail on `LeafContext.application`).
> Fix `LeafContext.application` Casting Failure

- Sources/Leaf/LeafEncoder.swift
- Tests/LeafTests/LeafMemoryGrowthTests.swift
I've noticed memory usage growth in my project that is described in https://github.com/vapor/leaf/issues/238 
After adding some tests and running `leaks`, I found that currently there are retain cycles. That PR fixes them.
That's what `leaks` printed (a lot of similar messages):
```bash
4 (352 bytes) ROOT CYCLE: <EncoderImpl 0x1572270d0> [80]
3 (272 bytes) storage --> ROOT CYCLE: <Leaf.LeafEncoder.(KeyedContainerImpl in _30C79F4310B915184892E56903FC555A)<CodingKeys in Foo #1 in closure #1 (Vapor.Application) async throws -> () in LeafTests.LeafMemoryGrowthTests.testRepeatedRenderMemoryGrowth() async throws -> ()> 0x157227120> [48]
__strong encoder --> CYCLE BACK TO <EncoderImpl 0x1572270d0> [80]
2 (224 bytes) __strong data._variant --> <Swift._DictionaryStorage<Swift.String, …
```
> Refactor encoder property to weak reference in KeyedContainerImpl and UnkeyedContainerImpl to prevent retain cycles
